#!/bin/bash

# First step is to determine whether the system is on SciNet or not
# Check current path

SCINET_REPO=/scinet/course/ss2019/3/6_mripython/

#If Scinet then enter first name to create Repo
if [ -d "$SCINET_REPO" ]; then

        echo "Please enter your first name (no spaces or special characters!)"
        read first_name
        mkdir -p $HOME/$first_name/
        git clone https://github.com/jerdra/scwg2018_python_neuroimaging.git $HOME/$first_name
        rm -rf "$HOME/$first_name/data"
        ln -s "$SCINET_REPO"/data $HOME/$first_name/data

        echo "Workshop at $HOME/$first_name"

#Otherwise we use a Binder instance
else

        echo "Assuming that you're using a Binder instance, downloading data!"

        # download fmriprep preprocessed anat data
        cat download_list | \
          xargs -I '{}' aws s3 sync --no-sign-request \
          s3://openneuro/ds000030/ds000030_R1.0.5/uncompressed/derivatives/fmriprep/{}/anat \
          ./data/ds000030/derivatives/fmriprep/{}/anat

        # download fmriprep preprocessed func data
        cat download_list | \
          xargs -I '{}' aws s3 sync --no-sign-request \
          s3://openneuro/ds000030/ds000030_R1.0.5/uncompressed/derivatives/fmriprep/{}/func \
          ./data/ds000030/derivatives/fmriprep/{}/func \
          --exclude '*' \
          --include '*task-rest_bold*'


fi
