#!/bin/bash

# Get directory of script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


# Set up for Binder Instance
echo "Setting up Test Workshop Data...."
(
	# Move into parent directory of script directory
	cd $DIR
	cd ..
	python ./binder/getData.py ./data/test_download ./data/ds000030
)
