#!/bin/bash

# Get directory of script
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"


# Set up for Binder Instance
echo "Setting up SDC-BIDS-fMRI Workshop...."
(
	# Move into parent directory of script directory
	cd $DIR
	cd ..
	python ./binder/getData.py ./data/download_list ./data/ds000030


)
